services:
  app:
    container_name: app
    build:
      context: ./application
      dockerfile: prod-without-multistage.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  postgres:
    env_file:
      - .env
    container_name: ${DB_CONTAINER_NAME}
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - ${DOCKER_NETWORK}

  pgadmin:
    env_file:
      - .env
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - 5050:80
    networks:
      - ${DOCKER_NETWORK}

networks:
  docker_network:
